Module2 task1
htmlacademy-javascript/1827273-keksobooking-23 pull request #3
Opened 2021-06-08 16:12 UTC by CheapSellsword

2021-06-08 21:41 UTC, ant1quar requested changes
Неплохо, немного подтюнить надо. глянь мои комменты ниже

2021-06-08 21:41 UTC, ant1quar commented on js/main.js
> +}
Почему-то в return не используется `min`

2021-06-08 21:41 UTC, ant1quar commented on js/main.js
> +  return Number((Math.random() * (max - min) + min).toFixed(decimals));
С преобразованием в Number ты правильно придумал. 👍 
toFixed же строку возвращает.

2021-06-08 21:41 UTC, ant1quar commented on js/main.js
> +  if (min >= max || min < 0) {
предложение. А почему-бы не менять местами min и max, если передали `min >= max`?

2021-06-08 21:41 UTC, ant1quar commented on js/main.js
> +    return ('Invalid range');
Возвращать строку в функции, которая должна генерировать число - как-то не хорошо.
Можем возвращать `null` - как число не задано.

2021-06-09 16:19 UTC, CheapSellsword commented on js/main.js
> +}
Исправил

2021-06-09 16:20 UTC, CheapSellsword commented on js/main.js
> +  return Number((Math.random() * (max - min) + min).toFixed(decimals));
Спасибо :)

2021-06-09 16:22 UTC, CheapSellsword commented on js/main.js
> +    return ('Invalid range');
Понял, логично. Исправил

2021-06-09 16:27 UTC, CheapSellsword commented on js/main.js
> +  if (min >= max || min < 0) {
Что-то типа автоматического исправления ошибки пользователя? Хорошо, сделаю :)

2021-06-10 21:17 UTC, merged