Нужна помощь
htmlacademy-javascript/1827273-keksobooking-23 pull request #5
Opened 2021-06-19 17:32 UTC by CheapSellsword

Функция getOffers (строка 79) возвращает 10 одинаковых предложений. Не могу понять как сделать правильно. 

Объект author (51). Не знаю как сделать так, чтобы номера изображений не повторялись. Еще заметил, что боту не понравилось это:

"Check failure on line 26 in js/main.js
GitHub Actions
/ Check
js/main.js#L26

>>> Unexpected string concatenation " <<<

Но как по-другому добавлять 0 перед однозначными числами, не превращая их в строку, я не знаю.

2021-06-20 20:58 UTC, ant1quar requested changes

2021-06-20 20:58 UTC, ant1quar commented on js/main.js
> +let offer = {
у тебя offer создается один раз, а не во время каждого вызова функции.
Объяви эту переменную в цикле в функции getOffers, тогда этот объект будет создаваться во время каждой итерации.

2021-06-20 20:58 UTC, ant1quar commented on js/main.js
> +let offer = {
Ну и с author такая же беда

2021-06-21 15:46 UTC, CheapSellsword commented on js/main.js
> +let offer = {
Понял, исправлю.

2021-06-22 14:09 UTC, ant1quar reviewed
Да, теперь правильно. Нужно только ошибки линтера проверить, но это уже в следующем коммите

2021-06-22 14:09 UTC, merged